server:
  log_level: debug

metrics:
  global:
    scrape_interval: 60s
    remote_write:
      - url: http://prometheus:9090/api/v1/write
  configs:
    - name: default

integrations:
  agent:
    enabled: true
    instance: default

traces:
  configs:
    - name: default
      receivers:
        jaeger:
          protocols:
            grpc:
            thrift_binary:
            thrift_compact:
            thrift_http:
      attributes:
        actions:
          - action: upsert
            key: env
            value: prod
      remote_write:
        - endpoint: tempo:4317
          insecure: true
      batch:
        timeout: 5s
        send_batch_size: 100
      automatic_logging:
        backend: stdout
        roots: true
        labels:
          - svc
          - status
      spanmetrics:
        handler_endpoint: 0.0.0.0:8889
      service_graphs:
        enabled: true
      tail_sampling:
        policies:
          - and:
              and_sub_policy:
                - type: string_attribute
                  string_attribute:
                    key: job
                    values:
                      - tns/db
                - type: string_attribute
                  string_attribute:
                    key: http.url
                    values:
                      - /metrics
